language: go

# must stay consistent with make/image.mk's GO_VERSION
go:
  - 1.16

env:
  - T=unit
  - T=integration
  - T=integration DEPLOY_METHOD=download
  - T=integration WITH_DEV_IMAGE=1
  - T=integration NUM_NODES=0 EXTRA_GMSA_DEPLOY_ARGS=--tolerate-master
  - T=integration WITHOUT_ENVSUBST=1
  - T=dry_run_deploy

script:
  - cd $TRAVIS_BUILD_DIR/admission-webhook && ./.travis.sh
